import { Poppins as segoe } from 'next/font/google'
import './globals.css'

const inter = segoe({
  subsets: ['latin'],
  weight: ['100', '400', '500', '700', '900']
})

export const metadata = {
  title: 'Creative Agency V1',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
